site_name: CÁLCULO II - FAMAF - UNC
site_url: https://tomasccc.github.io/CALCII-FAMAF-UNC/
repo_url: https://github.com/tomasccc/CALCII-FAMAF-UNC
repo_name: tomasccc/CALCII-FAMAF-UNC
edit_uri: edit/main/docs/

theme:
  name: material
  custom_dir: overrides  
  logo: assets/logo.png
  favicon: assets/logo2.png  
  features:
    - navigation.tabs
    - navigation.top
    - navigation.footer
    - navigation.tracking
    - navigation.prerender
    - search.highlight
    - search.share
    - search.full_text
    - search.math
    - search.suggest
  font:
    text: Inter
    code: Inter
  palette:
    - scheme: default
      primary: white
      accent: indigo
      toggle:
        icon: material/brightness-7
        name: Cambiar a modo oscuro
    - scheme: slate
      primary: black
      accent: light green
      toggle:
        icon: material/brightness-4
        name: Cambiar a modo claro

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/tomasccc
      name: Mi GitHub
    - icon: fontawesome/brands/linux
      link: https://linuxmint.com/
      name: Linux Mint
plugins:
  - search
  - social:
      cards_layout_options:
        background_color: "#3f51b5"  
        color: "#ffffff"            
        font_family: Inter
  - git-revision-date-localized:
      enable_creation_date: true
      type: timeago
      fallback_to_build_date: true
  - git-authors:
      show_contribution: true
      show_line_count: true           

hooks:
  - hooks.py

extra_css:
  - stylesheets/extra.css

markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.arithmatex:
      generic: true 

extra_javascript:
  - javascripts/mathjax.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js