local_backend: true
locale: es
backend:
  name: github
  repo: tomasccc/CALCII-FAMAF-UNC
  branch: cms-tests 

publish_mode: editorial_workflow

# Fundamental para que las imágenes se guarden y muestren bien
# Dónde guarda Sveltia el archivo real en tu código
media_folder: "docs/assets/comunidad"

# Cómo escribe Sveltia el enlace en el Markdown: ![](...)
public_folder: "/assets/comunidad"

collections:
  - name: "comunidad"
    label: "Aportes de la Comunidad"
    folder: "docs/comunidad"
    create: true
    extension: "md"
    format: "frontmatter"
    fields:
      - {label: "Título", name: "title", widget: "string"}
      - {label: "Contenido", name: "body", widget: "markdown"}